name: MegaTest

on:
  release:
      branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    # https://github.com/marketplace/actions/setup-steamcmd
    - name: Setup steamcmd
      uses: CyberAndrii/setup-steamcmd@v1
    # This next step may take a while...
    # - name: Install multiple games
    #    run: steamcmd +login anonymous +app_update 1172470 validate +quit
    # 1172470  Apex Legends
    # 440      Team Fortress 2
    # TODO: extract RESPAWN .bsps from special .vpks (or load directly from .vpks)
    # - name: Run tests on every .bsp
    # need to scrape all installed games and hand .bsps to test suite
    # export a file recording all failed tests & .bsp logs,
    # unknown lumps: lump sizes & patterns
